channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::python=3.10
  - conda-forge::anndata=0.10.9
  - conda-forge::numpy=1.26.4
  - conda-forge::scipy=1.13.0
  - conda-forge::scanpy=1.11.2
  - conda-forge::matplotlib=3.8.4
  - conda-forge::tqdm=4.66.4
  - bioconda::phenograph=1.5.7
  - conda-forge::psutil=5.9.8
  - conda-forge::pillow=10.3.0
  - conda-forge::pyparsing=3.1.2
  - conda-forge::pyyaml=6.0.2
  - conda-forge::pip=25.0.1
  - pip:
      - doubletdetection==4.3.0.post1
